config/routes.rb
AssetTrackerTutorial::Application.routes.draw do
  root :to => "dashboard/base#index"

  devise_for :users do
    get 'login', :to => 'devise/sessions#new'
    post 'login', :to => 'devise/sessions#create'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :invoices
    resources :payroll
    resources :users do
      member do
        get :projects
        post :projects
      end
    end
    resources :projects
    resources :unentered_time_report
    resources :weekly_time_report
  end
  get '/admin', :controller => "admin/base", :action => "index"

  resources :clients do
    resources :comments
    resources :contacts
  end

  resources :projects do
    resources :comments
  end

  resources :tickets do
    resources :comments
  end

  resources :work_units do
    resources :comments
  end

  resources :users do
    member do
      put :change_password
      get :historical_time
    end
  end

  resources :comments

  resources :file_attachments

  namespace :dashboard do
    resources :base do
    end
  end

  get '/dashboard', :controller => "dashboard/base", :action => "index"
  get '/dashboard/calendar', :controller => "dashboard/base", :action => "calendar"
  get '/dashboard/client', :controller => "dashboard/base", :action => "client"
  get '/dashboard/project', :controller => "dashboard/base", :action => "project"
  get '/dashboard/recent_work', :controller => "dashboard/base", :action => "recent_work"

  namespace :api do
    namespace :v1 do
      resources :clients
    end
  end
end

app/views/shared/_add_work_unit.html.haml
- content_for :javascripts do
  = javascript_include_tag "add_work_unit"

#add-work-unit
  %h4.dashboard_title Add Work Unit

  = form_for WorkUnit.new(params[:work_unit]) do |f|

    #work-unit-errors

    .work_unit_field
      %label Scheduled On:
      = link_to Time.current.strftime("%m/%d/%Y"), "#", :id => "schedule_modal_link"

    #schedule_modal
      %p It is best to enter work units on days you completed the work, please use this wisely.
      .work_unit_field
        %label Scheduled On:
        = text_field_tag :scheduled_at, Time.current.strftime("%m/%d/%Y")

    .work_unit_field
      %label{:for => "work_unit_client_id"} Client:
      = collection_select("work_unit", "client_id", @clients, "id", "name", { :prompt => "Select a client" })

    .work_unit_field
      %label{:for => "work_unit_project_id"} Project:
      = collection_select("work_unit", "project_id", @projects, "id", "name", { :prompt => "Select a project" })

    .work_unit_field
      %label{:for => "work_unit_ticket_id"} Ticket:
      = collection_select("work_unit", "ticket_id", @tickets, "id", "name", { :prompt => "Select a ticket" })

    .work_unit_field
      %label{:for => "hours_type"} Type:
      = select_tag('hours_type', options_for_select(['Normal', 'Overtime']))

    .work_unit_field
      %label{:for => "work_unit_hours"} Hours:
      = f.text_field :hours, { :size => 10 }

    .work_unit_field
      %label{:for => "work_unit_description"} Description:
      = f.text_area :description, { :rows => 10, :style => "resize: none;"}

      = f.hidden_field :scheduled_at
      = f.submit "Add New", :class => 'add_new_button'

app/views/shared/_calendar.html.haml
#calendar
  %table
    %thead
      %tr.calendar_top
        - (0..6).map{|x| start_date + x.days }.each do |date|
          %th= "#{date.asctime[0]} - #{date.day}"
        %th= "#{t(:totals)}:"
    %tfoot
      %tr.calendar_foot
        - (0..6).map{|x| start_date + x.days }.each do |date|
          %td= "#{t(:total)}: #{user.work_units_for_day(date).sum(:hours)}"
        %td= "#{t(:week)}: #{user.work_units_for_week(start_date).sum(:hours)}"
    %tbody
      %tr
        - (start_date..(start_date + 6.days)).each do |date|
          %td
            - unless user.work_units_for_day(date).empty?
              %ul
                - user.work_units_for_day(date).each do |work_unit|
                  %li{:class => "#{work_unit.overtime? ? 'work_unit overtime' : 'work_unit'}"}
                    = link_to "#{work_unit.client.initials}: #{work_unit.hours}", work_unit_path(work_unit), { :title => work_unit.description }
        %td= "#{t(:current)}: #{user.unpaid_work_units.sum(:hours)}"

app/views/shared/_flashes.html.haml
- if flash[:error]
  .yui3-g
    .yui3-u-1
      .gradient_border_wrap
        .gradient_border_content
          %p#flash_error= flash[:error]
- if flash[:notice]
  .yui3-g
    .yui3-u-1
      .gradient_border_wrap
        .gradient_border_content
          %p#flash_notice= flash[:notice]

app/views/shared/_javascripts.html.haml
= javascript_include_tag 'css_browser_selector', :defaults
= yield :javascripts

app/views/shared/_menu.html.haml
%ul
  %li= link_to t(:home), root_path
  %li= link_to t(:clients), clients_path
  - if admin?
    %li= link_to t(:users), admin_users_path
    %li= link_to t(:admin), admin_path
  - else
    %li= link_to t(:users), users_path