config/routes.rb
AssetTrackerTutorial::Application.routes.draw do
  root :to => "dashboard/base#index"

  devise_for :users do
    get 'login', :to => 'devise/sessions#new'
    post 'login', :to => 'devise/sessions#create'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :invoices
    resources :payroll
    resources :users do
      member do
        get :projects
        post :projects
      end
    end
    resources :projects
    resources :unentered_time_report
    resources :weekly_time_report
  end
  get '/admin', :controller => "admin/base", :action => "index"

  resources :clients do
    resources :comments
    resources :contacts
  end

  resources :projects do
    resources :comments
  end

  resources :tickets do
    resources :comments
  end

  resources :work_units do
    resources :comments
  end

  resources :users do
    member do
      put :change_password
      get :historical_time
    end
  end

  resources :comments

  resources :file_attachments

  namespace :dashboard do
    resources :base do
    end
  end

  get '/dashboard', :controller => "dashboard/base", :action => "index"
  get '/dashboard/calendar', :controller => "dashboard/base", :action => "calendar"
  get '/dashboard/client', :controller => "dashboard/base", :action => "client"
  get '/dashboard/project', :controller => "dashboard/base", :action => "project"
  get '/dashboard/recent_work', :controller => "dashboard/base", :action => "recent_work"

  namespace :api do
    namespace :v1 do
      resources :clients
    end
  end
end

app/controllers/admin/unentered_time_report_controller.rb
class Admin::UnenteredTimeReportController < ApplicationController

  def index
    redirect_to("/admin/unentered_time_report/#{Date.current.beginning_of_week.to_s}")
  end

  def show
    redirect_unless_monday('/admin/unentered_time_report/', params[:id])
    @week_dates = build_week_hash_for(Date.parse(params[:id]))
    @users = User.select{|u| u.has_role?(:developer) && !u.locked }
  end

end

app/views/admin/unentered_time_report/show.html.haml
.yui3-g
  .yui3-u-1
    %h2= t(:users_with_no_time_entered)
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        - @week_dates.each do |weekday, date|
          %div{:id => weekday}
            %h3= "#{weekday}, #{date.to_formatted_s(:long_ordinal)}"
            - if date.past?
              %ul
                - for user in @users do
                  - unless user.work_units_for_day(date).any?
                    %li= link_to user, user_path(user)

        %h4= link_to t(:previous), admin_unentered_time_report_path(@week_dates["Monday"] - 1.week)
        %h4= link_to t(:next), admin_unentered_time_report_path(@week_dates["Monday"] + 1.week)