config/routes.rb
AssetTrackerTutorial::Application.routes.draw do
  root :to => "dashboard/base#index"

  devise_for :users do
    get 'login', :to => 'devise/sessions#new'
    post 'login', :to => 'devise/sessions#create'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :invoices
    resources :payroll
    resources :users do
      member do
        get :projects
        post :projects
      end
    end
    resources :projects
    resources :unentered_time_report
    resources :weekly_time_report
  end
  get '/admin', :controller => "admin/base", :action => "index"

  resources :clients do
    resources :comments
    resources :contacts
  end

  resources :projects do
    resources :comments
  end

  resources :tickets do
    resources :comments
  end

  resources :work_units do
    resources :comments
  end

  resources :users do
    member do
      put :change_password
      get :historical_time
    end
  end

  resources :comments

  resources :file_attachments

  namespace :dashboard do
    resources :base do
    end
  end

  get '/dashboard', :controller => "dashboard/base", :action => "index"
  get '/dashboard/calendar', :controller => "dashboard/base", :action => "calendar"
  get '/dashboard/client', :controller => "dashboard/base", :action => "client"
  get '/dashboard/project', :controller => "dashboard/base", :action => "project"
  get '/dashboard/recent_work', :controller => "dashboard/base", :action => "recent_work"

  namespace :api do
    namespace :v1 do
      resources :clients
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include GuidReferenced
  acts_as_commentable
  acts_as_authorization_object

  belongs_to :client
  has_many :tickets
  has_many :comments, :as => :commentable
  has_many :file_attachments

  validates_presence_of :name
  validates_presence_of :client_id
  validates_uniqueness_of :name, :scope => :client_id

  def uninvoiced_hours
    WorkUnit.for_project(self).not_invoiced.inject(0) {|sum, w| sum + w.hours}
  end

  def total_hours
    WorkUnit.for_project(self).inject(0) {|sum, w| sum + w.hours}
  end

  def total_work_units
    tickets.inject(0) {|sum, t| sum + t.work_units.count}
  end

  def self.for_user(user)
    select {|p| p.allows_access?(user) }
  end

  def hours
    tickets.inject(0) {|sum, t| sum + t.hours}
  end

  def to_s
    name
  end

  def allows_access?(user)
    accepts_roles_by?(user) || user.admin?
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :load_new_project, :only => [:new, :create]
  before_filter :load_project, :only => [:show, :edit, :update]
  before_filter :load_file_attachments, :only => [:show, :new, :create]
  access_control do
    allow :admin
    allow :developer, :of => :project
    allow :client, :of => :project
  end

  protected
  def load_new_project
    @project = Project.new(params[:project])
    @project.client = Client.find(params[:client])
  end

  def load_project
    @project = Project.find(params[:id])
  end

  def load_file_attachments
    @file_attachments = @project.file_attachments
  end

  public

  def show
    @tickets = @project.tickets.sort_by{|ticket| ticket.name.downcase}
  end

  def new
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = t(:project_updated_successfully)
      redirect_to [@project]
    else
      flash.now[:error] = t(:project_updated_unsuccessfully)
      render :action => 'edit'
    end
  end

  def create
    if @project.save
      flash[:notice] = t(:project_created_successfully)
      redirect_to @project
    else
      flash.now[:error] = t(:project_created_unsuccessfully)
      render :action => 'new'
    end
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        = "#{t(:prohibited_this_project_from_being_saved)}:"

      %ul
      - @project.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.label :name
    = f.text_field :name
    = hidden_field_tag :client, @project.client.id
  .actions
    = f.submit :class => "add_new_button"
    = link_to t(:cancel), client_path(@project.client)

app/views/projects/edit.html.haml
.yui3-g
  .yui3-u-1
    %h2= "#{t(:edit_project)} #{@project}"
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        = render 'form'

app/views/projects/new.html.haml
.yui3-g
  .yui3-u-1
    %h2= t(:new_project)
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        = render 'form'

app/views/projects/show.html.haml
.yui3-g
  .yui3-u-1
    %h2= "#{@project.client}: #{@project}"
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        %ul.subnav
          %li= link_to t(:edit), edit_project_path
          %li= link_to "#{t(:back_to_client)}: #{@project.client}" , @project.client
          %li= link_to t(:new_ticket), new_ticket_path(:project_id => @project)
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        %h3= "#{t(:status)}: #{@project.client.status}"
        %table.tickets
          %thead
            %tr
              %th= t(:tickets)
              %th= t(:work_units)
              %th= t(:uninvoiced_hours)
              %th= t(:total_hours)
              %th= t(:edit)
          %tfoot
            %tr
              %th= t(:all_tickets)
              %th= @project.total_work_units
              %th= @project.uninvoiced_hours
              %th= @project.total_hours
              %th &nbsp;
          %tbody
            - @tickets.each do |ticket|
              %tr
                %td= link_to ticket, ticket
                %td= ticket.work_units.count
                %td= ticket.uninvoiced_hours
                %td= ticket.hours
                %td= link_to t(:edit), edit_ticket_path(ticket)
.yui3-g
  .yui3-u-1-2
    .gradient_border_wrap
      .gradient_border_content
        = render :partial => "comments/comments", :locals => {:comments => @project.comments}
        = render :partial => "comments/comment_form", :locals => { :commentable_id => @project.id,
          :commentable_field => "project_id",
          :commentable_type => "Project",
          :refurl => project_path(@project),
          :comment_num => @project.id }
  .yui3-u-1-2
    .gradient_border_wrap
      .gradient_border_content
        %h2= t(:files)
        %ul
          - @project.file_attachments.each do |file_attachment|
            %li= link_to file_attachment.attachment_file_file_name, file_attachment_path(file_attachment.id)
        = link_to t(:add_file_attachment), new_file_attachment_path( :project_id => @project.id )