config/routes.rb
AssetTrackerTutorial::Application.routes.draw do
  root :to => "dashboard/base#index"

  devise_for :users do
    get 'login', :to => 'devise/sessions#new'
    post 'login', :to => 'devise/sessions#create'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :invoices
    resources :payroll
    resources :users do
      member do
        get :projects
        post :projects
      end
    end
    resources :projects
    resources :unentered_time_report
    resources :weekly_time_report
  end
  get '/admin', :controller => "admin/base", :action => "index"

  resources :clients do
    resources :comments
    resources :contacts
  end

  resources :projects do
    resources :comments
  end

  resources :tickets do
    resources :comments
  end

  resources :work_units do
    resources :comments
  end

  resources :users do
    member do
      put :change_password
      get :historical_time
    end
  end

  resources :comments

  resources :file_attachments

  namespace :dashboard do
    resources :base do
    end
  end

  get '/dashboard', :controller => "dashboard/base", :action => "index"
  get '/dashboard/calendar', :controller => "dashboard/base", :action => "calendar"
  get '/dashboard/client', :controller => "dashboard/base", :action => "client"
  get '/dashboard/project', :controller => "dashboard/base", :action => "project"
  get '/dashboard/recent_work', :controller => "dashboard/base", :action => "recent_work"

  namespace :api do
    namespace :v1 do
      resources :clients
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :lockable
  include Gravtastic
  gravtastic
  is_gravtastic!
  acts_as_authorization_subject :association_name => :roles

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :middle_initial

  validates_presence_of :first_name, :last_name
  validates_length_of :middle_initial, :is => 1

  has_many :work_units

  # Scopes
  scope :with_unpaid_work_units, joins(:work_units).where(' work_units.paid IS NULL OR work_units.paid = "" ').group('users.id')
  scope :unlocked, where('locked_at IS NULL')

  # Return the initials of the User
  def initials
    "#{first_name[0]}#{middle_initial}#{last_name[0]}".upcase
  end

  def work_units_for_day(time)
    work_units.scheduled_between(time.beginning_of_day, time.end_of_day)
  end

  def clients_for_day(time)
    work_units_for_day(time).map{|x| x.client}.uniq
  end

  def work_units_for_week(time)
    work_units.scheduled_between(time.beginning_of_week, time.end_of_week)
  end

  def unpaid_work_units
    work_units.unpaid
  end

  def to_s
    "#{first_name.capitalize} #{middle_initial.capitalize} #{last_name.capitalize}"
  end

  def admin?
    has_role?(:admin)
  end

  def locked
    locked_at?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :load_user_account, :only => [:update, :edit, :destroy, :projects]
  before_filter :load_new_user_account, :only => [:new, :create]

  def index
    @users = User.all.sort_by {|user| user.first_name.downcase}
  end

  def new
  end

  def create
    @user.update_attributes(params[:user])
    if @user.save
      flash[:notice] = t(:user_created_successfully)
      redirect_to admin_users_path
    else
      flash[:error] = t(:user_created_unsuccessfully)
      redirect_to new_admin_user_path
    end
  end

  def edit
  end

  def update
    if params[:user]["locked"] == "1" && !@user.locked_at?
      @user.lock_access!
    elsif params[:user]["locked"] == "0" && @user.locked_at?
      @user.unlock_access!
    end

    if params[:user]["password"] == "" && params[:user]["password_confirmation"] == ""
      params[:user].delete(:password) && params[:user].delete(:password_confirmation)
    end

    @user.update_attributes(params[:user])
    if @user.save
      flash[:notice] = t(:user_updated_successfully)
      redirect_to user_path(@user)
    else
      flash[:error] = t(:user_updated_unsuccessfully)
      redirect_to edit_admin_user_path(@user)
    end
  end

  def projects
    if request.post?
      params[:project].each do |key, value|
        project = Project.find(key.to_i)
        role = value.to_sym
        @user.has_no_roles_for!(project)
        @user.has_role!(role, project) unless role == :no_access
      end
      flash[:notice] = t(:roles_updated_successfully)
      redirect_to admin_users_path
    end
  end

private

  def load_user_account
    @user = User.find(params[:id])
  end

  def load_new_user_account
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_user, :only => [:show, :edit, :change_password, :historical_time]
  before_filter :require_current_user, :only => [:edit, :change_password]

  def index
    @users = User.unlocked.sort_by {|user| user.first_name.downcase}
  end

  def show
  end

  def edit
  end

  def change_password
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      flash[:notice] = t(:password_updated_successfully)
      redirect_to :action => :show
    else
      params[:user][:password] = params[:user][:password_confirmation] = ''
      flash.now[:error] = t(:password_updated_unsuccessfully)
      render :action => :edit
    end
  end

  def historical_time
  end

  protected

    def load_user
      @user = User.find(params[:id])
    end

    def require_current_user
      unless @user == current_user
        flash[:error] = t(:cannot_make_changes_to_another_user)
        redirect_to dashboard_path
      end
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.haml
.yui3-g
  .yui3-u-1
    %h2= t(:edit_user)
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        = form_for @user, :class => "new_user", :url => admin_user_path(@user) do |f|
          .field_wrap
            = f.label :first_name
            = f.text_field :first_name
          .field_wrap
            = f.label :last_name
            = f.text_field :last_name
          .field_wrap
            = f.label :middle_initial
            = f.text_field :middle_initial
          .field_wrap
            = f.label :email
            = f.text_field :email
          .field_wrap
            = f.label :password
            = f.password_field :password
          .field_wrap
            = f.label :password_confirmation
            = f.password_field :password_confirmation
          .field_wrap
            = f.label :locked
            = f.check_box :locked
          .field_wrap
            = f.submit 'Update', :class => 'add_new_button'
            = link_to 'Cancel', admin_users_path, :class => 'cancel_button'

        .clear

app/views/admin/users/index.html.haml
.yui3-g
  .yui3-u-1
    %h2= t(:all_users)
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        %table.users
          %thead
            %tr
              %th= t(:name)
              %th= t(:email)
              %th= t(:current)
              %th= "#{t(:locked)}?"
              %th= t(:roles)
              %th= t(:edit)
          %tbody
            - @users.each do |user|
              %tr
                %td.user_img
                  = link_to "#{show_gravatar_for(user)}<span>#{user}</span>".html_safe,
                    user_path(user)
                %td= user.email
                %td= user.unpaid_work_units.sum(:hours)
                %td= user.locked_at? ? 'X' : '&nbsp;'.html_safe
                %td
                  - if user.admin?
                    = t(:admin)
                  - else
                    = link_to t(:roles), projects_admin_user_path(user)
                %td= link_to t(:edit), edit_admin_user_path(user)
        = link_to t(:new_user), new_admin_user_path, :class => "add_new_button"

app/views/admin/users/new.html.haml
.yui3-g
  .yui3-u-1
    %h2= t(:new_user)
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        = form_for @user, :class => "new_user", :url => admin_users_path do |f|
          = f.label :first_name
          = f.text_field :first_name
          %br/
          = f.label :last_name
          = f.text_field :last_name
          %br/
          = f.label :middle_initial
          = f.text_field :middle_initial
          %br/
          = f.label :email
          = f.text_field :email
          %br/
          = f.label :password
          = f.password_field :password
          %br/
          = f.label :password_confirmation
          = f.password_field :password_confirmation
          %br/
          = f.submit t(:create), :class => 'add_new_button'

          = link_to t(:cancel), admin_users_path, :class => 'cancel_button' 

          .clear

app/views/admin/users/projects.html.haml
.yui3-g
  .yui3-u-1
    %h2
      = @user
      =t(:roles)
.yui3-g
  .yui3-u-1
    .gradient_border_wrap
      .gradient_border_content
        = form_tag(projects_admin_user_path, :method => 'post') do
          %table
            %thead
              %th= t(:client)
              %th= t(:project)
              %th= t(:developer_role)
              %th= t(:client_role)
              %th= t(:no_roles)
            - Client.all.sort_by{|c| c.name.downcase}.each do |client|
              - client.projects.sort_by{|p| p.name.downcase}.each do |project|
                %tr
                  %td= client
                  %td= project
                  %td= radio_button_tag("project[#{project.id}]", "developer", @user.has_role?(:developer, project))
                  %td= radio_button_tag("project[#{project.id}]", "client", @user.has_role?(:client, project))
                  %td= radio_button_tag("project[#{project.id}]", "no_access", @user.roles_for(project).empty?)
          = submit_tag("Submit")